spring:
  application:
    name: perdix-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: rajesh_app_route
        uri: lb://rajesh_app
        predicates:
        - Path=/rajesh-app/**
        filters:
        #- Logging
  security:
    user1: rajesh
    password1: jsm
    basic:
      enabled: false
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://produat-kinara-db.nva.perdix.co:3306/financialForms?useUnicode=true&characterEncoding=utf8
    username: financialForms
    password: financialForms
  devtools:
    restart:
      enabled: true
application:
  name: perdix-server
  secretKeys:
    ifmruser: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAou7LqbtFbp7+vZR4lvNW1ph6xVYN22SAlp7wDcO0eIWRM8uR0iCHZ7Gg0U/5rO/hgAYNZZhO+JT69fE714LrnEOckKV382KOZ0H+tc0/MODivRSl/4V4J1mJv9E079MsWyWALxiYvJNHXf3kKR9L6FVGZq6witwyhhGcBXNih6A/HiemFyOLmcwHGFNix85RGkxR7NkcRuV5qX2HRa5dgGMOwakKBcZT/Vvbakw5/J0oUttddVUM8Bs5U1RTW/sw2SEFQha1DCgbXCjyof13U3kIY+cxq9ABvjjiSd3psX6SfIplsNkxROzxRVFCJtFnqDQD3rdCB13/PBEDHh4nhwIDAQAB
server:  
      port: 7070
      servlet: 
        context-path: /auth  
user: 
  oauth: 
    clientId: perdix_client
    clientSecret: perdix_secret
    user:
      username: rk
      password: 1234
logging: 
  level:
    '[org.springframework.cloud.gateway]': DEBUG
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

